export const types = {
	SET_DARK_THEME: 'SET_DARK_THEME',
	SET_LIGHT_THEME: 'SET_LIGHT_THEME',

	CREATE_CONTRIBUTER_START: 'CREATE_CONTRIBUTER_START',
	CREATE_CONTRIBUTER_SUCCESS: 'CREATE_CONTRIBUTER_SUCCESS',
	CREATE_CONTRIBUTER_FAILED: 'CREATE_CONTRIBUTER_FAILED',

	UPDATE_CONTRIBUTER_START: 'UPDATE_CONTRIBUTER_START',
	UPDATE_CONTRIBUTER_SUCCESS: 'UPDATE_CONTRIBUTER_SUCCESS',
	UPDATE_CONTRIBUTER_FAILED: 'UPDATE_CONTRIBUTER_FAILED',
}